### ISSUE TITLE
Look into github -> discord API

### ISSUE THREAD

**Issue by KevinMGranger** [gecko231/DogArm#8]
Why not, eh?

**Comment by KevinMGranger** [comment]
Never mind, that's in the up-and-coming section :/

**Comment by abe8591** [comment]
Maybe something to look at in the meantime? https://github.com/Falconerd/discord-bot-github/blob/master/README.md

**Comment by KevinMGranger** [comment]
Ooh, the Discord page implied the feature didn't exist yet... nice. I'll look into that.

**Comment by KevinMGranger** [comment]
This is functional as soon as greg adds the hook to the repo.
